# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Comments
wrap_comments = true
comment_width = 100
normalize_comments = true

# Misc
use_small_heuristics = "Default"
fn_call_width = 80
struct_lit_width = 40
struct_variant_width = 40
array_width = 80
chain_width = 80

# Formatting
format_code_in_doc_comments = true
format_strings = true
format_macro_bodies = true

# Style
use_field_init_shorthand = true
force_explicit_abi = true
