# Clippy linting configuration
# https://doc.rust-lang.org/clippy/

# Set the MSRV (Minimum Supported Rust Version)
msrv = "1.75.0"

# Complexity lints
too-many-arguments-threshold = 8
type-complexity-threshold = 500

# Cognitive complexity
cognitive-complexity-threshold = 50

# Don't warn about these
allow-unwrap-in-tests = true
allow-expect-in-tests = true
