base:
  role: "validator"
  data_dir: "/opt/aptos/var/data"
  waypoint:
    from_file: "/opt/aptos/var/genesis/waypoint.txt"

execution:
  genesis_file_location: "/opt/aptos/var/genesis/genesis.blob"

consensus:
  safety_rules:
    service:
      type: "local"
    backend:
      type: "on_disk_storage"
      path: "/opt/aptos/var/data/safety-rules.bin"
    initial_safety_rules_config:
      from_file:
        identity_blob_path: "/opt/aptos/var/identity/validator-identity.yaml"
        waypoint:
          from_file: "/opt/aptos/var/genesis/waypoint.txt"

validator_network:
  discovery_method: "onchain"
  listen_address: "/ip4/0.0.0.0/tcp/6180"
  mutual_authentication: true
  identity:
    type: "from_file"
    path: "/opt/aptos/var/identity/validator-identity.yaml"

full_node_networks: []

api:
  enabled: true
  address: "0.0.0.0:8080"

storage:
  rocksdb_configs:
    enable_storage_sharding: false
