[package]
name = "AtomicaAuction"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/bomba-atomica/atomica-aptos.git", subdir = "aptos-move/framework/aptos-framework", rev = "dev-atomica" }

[addresses]
atomica = "_"

[dev-addresses]
atomica = "0xcafe"
