[package]
name = "AtomicaAuction"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "../zapatos/aptos-move/framework/aptos-framework" }

[addresses]
atomica = "_"

[dev-addresses]
atomica = "0xcafe"
